### PR TITLE
Made the countries of the globe have varying colours

### PR DESCRIPTION
**Pull request by dolphingarlic**

### CODE REVIEW

**Comment by JPJPJPOPOP** [comment]
Several comments:
1. The green color makes the green lines hard to see. We need some other color that is not green, red, yellow, orange or blue
2. As discussed with firespeaker, we are planning to just scrap the modal. Instead when you click on a language, it should do the same exact thing as if using the language filter (rotate to it and show neighbors). Maybe zooming in would be nice too.
3. The color by stems setting is broken. I think when you moved around the colorbrewer code it messed the setting up somehow.

**Comment by JPJPJPOPOP** [comment]
1. Is it just me or is clicking on a node "laggy"? It seems to just jump directly onto the point. Would be nice if there was a nice rotating transition like when selecting from the language filter setting.
2. Are we going to get a background? Because currently it's just plain black.
3. For the color by stage/color by stem setting, I think they are flipped (it should show color by stage when the connections are solid colors and show color by stem when using the colorbrewer). I also think that keeping some kind of checkbox is necessary because it otherwise doesn't immediately stand out as something you can interact with.

**Comment by dolphingarlic** [comment]
I think instead of a text box, the buttons should change colour when the cursor hovers over them. Also, for the background, must it be dynamic? The one you showed me in the issue used d3 version 3, which is quite different from the current version 4

**Comment by JPJPJPOPOP** [comment]
You mentioned this background: https://bl.ocks.org/sarah37/d5d1a482e4454586e3188e325f37c994, which is fine for now.

**Comment by dolphingarlic** [comment]
To make the clicking less laggy, I had to take out the zoom when clicked, because d3 tries to do both at the same time. Also, the color by stage/color by stem setting isn't switched: when it says "Colour by Stage" and you press it, it is meant to change the colouring from stems to stage

**Comment by dolphingarlic** [comment]
Is the jade colour for the countries fine? It doesn't seem to obscure anything, and it looks quite natural. I can always change the border/stroke colour as well if that's a problem

**Pull request merged**
