### PR TITLE
Scraped new data and added new languages

### PR DESCRIPTION
**Pull request by JPJPJPOPOP**
- Scraped new data for pairs.json.txt
- Added new languages into apertium-languages.tsv
- Made rotation to language activate after all filtering is done to make it smoother
- Added functionality to add the new pairs on top of the current default pairs

### CODE REVIEW

**Comment by jonorthwash** [comment]
> 1. https://github.com/jonorthwash/Apertium-Global-PairViewer/issues/26#issuecomment-354708419.

https://github.com/jonorthwash/Apertium-Global-PairViewer/issues/26#issuecomment-355123107

> 2. The globe is now super crowded. Should it be like this? Is there a way to make it look nicer?

Fixing the colours would be a good start, I think.  Also, perhaps it should load with production-level languages by default.

> 3. The program gets laggy when filtering.

I guess that's to be expected to some extent.  But perhaps there are ways to make the code more efficient.  If you can't figure it out yourself, add this as an issue.

**Comment by jonorthwash** [comment]
Where's the scraper?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Took from here: https://svn.code.sf.net/p/apertium/svn/trunk/apertium-tools/get_all_lang_pairs.py

**Comment by jonorthwash** [comment]
It produces data we can use without any modification, right?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash How did you use it? I just ran it which printed out all the pairs. Then I had to add commas to the end of them. I added a bunch of the new points manually. After, I ran the trimpairs.py program.

**Comment by jonorthwash** [comment]
I haven't used it yet; I'm just asking for future reference.  Could you give a point-by-point list of how to import data using the different scripts (with links to them)?  Maybe in a README somewhere?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash oh okay sure

**Pull request merged**
