### PR TITLE
Stars now move with globe

### LINKED ISSUE #29: Globe and background color
Currently, the globe is a bit bland with only two solid colors, white for land, and light blue for water.

It would be nice if the colors weren't solid but based off of some other information (terrain?).

The background is also a solid color, maybe add something related to space?

### PR DESCRIPTION
**Pull request by diogoscf**
Final thing needed to resolve #29 

The space (background), including the stars, now zooms in and out, and moves around too with the zooming and rotating of the globe.

[Here is a video of the code in action](https://imgur.com/a/Puuklc5)

### CODE REVIEW

**Comment by JPJPJPOPOP** [comment]
@diogoscf I can't rotate the globe anymore for some reason. It's giving me `TypeError: t is undefined` in console.

**Comment by JPJPJPOPOP** [comment]
Never mind, something was wrong with my computer.

**Comment by JPJPJPOPOP** [comment]
@diogoscf Can you limit more how much you can zoom out because otherwise something like this happens:
Screen Shot 2019-12-11 at 1 57 05 PM

**Comment by JPJPJPOPOP** [comment]
Also, I am still getting `TypeError: stars is undefined` when I first load the page.

**Comment by diogoscf** [comment]
You can't zoom out as much now, and there are no more errors.

**Comment by JPJPJPOPOP** [comment]
LGTM

**Pull request merged**
