### PR TITLE
Add shadow toggle, improved globe and flyer UI

### LINKED ISSUE #21: Fix colors of flyers
Currently the flyers have a bad color scheme:

screen shot 2017-12-24 at 9 18 57 pm

Here is the current color scheme:
screen shot 2017-12-24 at 10 15 45 pm

Colors like from trunk, staging, and nursery look too similar.

### PR DESCRIPTION
**Pull request by JPJPJPOPOP**
- Changed locations of tat and chv
- Removed more pairs toggle
- Added shadow toggle
- Changed country border colors so they don't look like rivers

- Fixes #21, changed flyer colors:
screen shot 2018-01-07 at 1 03 38 am
Comments about flyer colors:
- The green and the yellow are pretty bright, so they stand out decently.
- The orange are a bit dark but I think it is okay.
- The red is terribly annoying to get right because of the opacity of the flyers. The opacity renders pure red as a fiery orange. Any lighter red turns very light, and anything dark turns muddy. Think #de1738 is okay.

- Added color saturation by stem and stem/pair info when mouseover flyer:
screen shot 2018-01-08 at 11 25 49 pm

- Fix bug where tooltip still shows for hidden points and labels
- Made points/labels appear on top of flyers/arcs
- Add color by stem toggle
- Added hover animation to flyer so it makes it easier to tell which flyer you are hovering on

### CODE REVIEW

**Comment by jonorthwash** [comment]
Can we do line thickness and/or lightness/saturation differences for dictionary size?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Do you mean like stem count?

**Comment by jonorthwash** [comment]
Yeah, dictionary size = stem count.

**Comment by jonorthwash** [comment]
What's the logic / divisions you used for dictionary size?  Is there a way to filter by dictionary size?

**Comment by jonorthwash** [comment]
The arrows don't seem to take the saturation changes.  Also, I think it would look better if the arrows didn't have black outlines (maybe unless the flyer is hovered?).

**Comment by JPJPJPOPOP** [comment]
@jonorthwash The division is the same as the pairviewer, like this:
screen shot 2018-01-10 at 5 59 50 pm

I should probably add a filter.

I purposefully made the arrows not take the saturation changes because I thought I would make it easier for people to distinguish the repo for flyers more easily. I could change that it you want to.

**Pull request merged**
